package org.acme.insurance.policyquote;

import org.acme.insurance.Driver
import org.acme.insurance.Policy


rule "SafeYouths"

    when
        
        driver : Driver(age >= 18 && <25, numberOfAccidents < 1,numberOfTickets <=1)
        policy : Policy(price == null, policyType == "AUTO")
        
    then
    
        modify(policy) {setPrice(450)};
        System.out.println("fired rule " + kcontext.getRule().getName());

end
        


